# -*- coding: utf-8 -*-
"""pytorchocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_f-zilSOaNSL0DMzXeVgP4x87QIcVQP
"""

!pip install easyocr
import easyocr
import PIL
import os

#Load the image
image = PIL.Image.open("Assignment.png")

#Initialize easyocr reader
reader = easyocr.Reader(['en'])

#Use the reader to detect the text in the photo
result = reader.readtext(image_path)

for r in result:
  print(r[1])

