# Generated by Django 4.1.6 on 2023-02-19 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUploadedFiles",
            fields=[
                (
                    "file_name",
                    models.CharField(help_text="Name of the file", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path of the file that user has uploaded",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for every uploaded file",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uploaded_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When did the user uploaded the file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who uploaded the object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
