# Generated by Django 4.1.6 on 2023-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summIApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useruploadedfiles",
            name="is this file public",
            field=models.BooleanField(default=False),
        ),
    ]
