# Generated by Django 4.1.7 on 2023-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summIApp", "0003_remove_useruploadedfiles_is this file public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useruploadedfiles",
            name="is_file_uploaded_on_imgbb",
            field=models.BooleanField(
                default=True, help_text="is this file uploaded in the imgbb server"
            ),
        ),
    ]
