# Generated by Django 4.1.7 on 2023-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summIApp", "0004_useruploadedfiles_is_file_uploaded_on_imgbb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useruploadedfiles",
            name="is_file_uploaded_on_imgbb",
            field=models.BooleanField(
                default=False, help_text="is this file uploaded in the imgbb server"
            ),
        ),
    ]
